mqtt:
    sensor:
        - name: plant_moisture
          state_topic: "sensor/soil_moisture"
          value_template: "{{ value_json.value }}"
          device:
              name: "Plant Moisture"
              identifiers:
                  - "plant_moisture"

        - name: light_intensity
          state_topic: "sensor/light_intensity"
          value_template: "{{ value_json.value }}"
          device:
              name: "Light Intensity"
              identifiers:
                  - "light_intensity"

        - name: "Plant name"
          state_topic: "config/plant_name"
          device:
              name: "Plant Name"
              identifiers:
                  - "plant_name"

history:
    include:
        entities:
            - sensor.plant_moisture
            - sensor.light_intensity

recorder:
    include:
        entities:
            - sensor.plant_moisture
            - sensor.light_intensity
